import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vikas_sharma
 */
public class bagmati extends javax.swing.JFrame {

    /**
     * Creates new form bagmati
     */
    public bagmati() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("TRAVEL DETAILS");

        jLabel2.setText("DESTINATION ");

        jLabel3.setText("DATE");

        jLabel4.setText("SOURCE ");

        jRadioButton1.setText("SLEEPER");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("AC");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYSORE", "KANGERI", "KSR BENGALURU", "KR PURAM", "JOLARPET", "CHENNAI", "VIJAYWADA", "NAGPUR", "BETUL", "ITARSI", "JABALPUR", "ALLAHABAAD", "DIN DHAYAL UPADHYAY", "BUXAR", "ARRA", "DANAPUR", "PATNA", "SAMASTIPUR", "MUZAFFARPUR", "DARBHANGA" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYSORE", "KANGERI", "KSR BENGALURU", "KR PURAM", "JOLARPET", "CHENNAI", "VIJAYWADA", "NAGPUR", "BETUL", "ITARSI", "JABALPUR", "ALLAHABAAD", "DIN DHAYAL UPADHYAY", "BUXAR", "ARRA", "DANAPUR", "PATNA", "SAMASTIPUR", "MUZAFFARPUR", "DARBHANGA" }));

        jLabel5.setText("ENTER NAME");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("NOTE:FOR CANCELLATION ENTER YOUR NAME,DATE,CLASS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(jLabel6)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jRadioButton2.isSelected())
        {
            String n=jTextField1.getText();
            int q=jComboBox2.getSelectedIndex();
            int i=0;
            int p=jComboBox1.getSelectedIndex();
            String str1 = Integer.toString(p);
            String str2 = Integer.toString(q);
            int[] sour=new int[50];
            int[] dest=new int[50];

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Locale.getDefault();
            String d=sdf.format(jDateChooser1.getDate());
            try
            {
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                String sql="Select * from b_res_ac where dat=? ";
                java.sql.PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,d);
                java.sql.ResultSet rs=pst.executeQuery();
                int found=0;
                while(rs.next())
                {
                    found++;
                }
                if(found==0)
                {Class.forName("java.sql.DriverManager");
                    java.sql.Connection con1 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                    java.sql.Statement stmt1 =con1.createStatement();
                    String query1="INSERT INTO b_res_ac VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                    int rs1=stmt1.executeUpdate(query1);
                    JOptionPane.showMessageDialog(null,"TICKET IS BOOKED VIA RAILWAY WALLET!");
                    System.exit(0);
                }
                else
                {
                    Class.forName("java.sql.DriverManager");
                    java.sql.Connection con2 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");
                    String sql2="Select si,di from b_res_ac where dat=? ";
                    java.sql.PreparedStatement pst2=con2.prepareStatement(sql2);
                    pst2.setString(1,d);
                    java.sql.ResultSet rs2=pst.executeQuery();
                    while(rs2.next())
                    {
                        sour[i]=rs2.getInt("si");
                        dest[i]=rs2.getInt("di");
                        if((p==sour[i])&&(q==dest[i]))
                        {
                            JOptionPane.showMessageDialog(null,"NO TICKETS AVILABLE ON SLECTED DATE PLEASE TRY OTHER DATE");
                            break;
                        }
                        if((q<=sour[i]||p>=dest[i]))
                        {

                            Class.forName("java.sql.DriverManager");
                            java.sql.Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                            java.sql.Statement stmt3 =con3.createStatement();
                            str1= Integer.toString(p);
                            str2 = Integer.toString(q);
                            String query3="INSERT INTO b_res_ac VALUimport com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vikas_sharma
 */
public class bagmati extends javax.swing.JFrame {

    /**
     * Creates new form bagmati
     */
    public bagmati() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("TRAVEL DETAILS");

        jLabel2.setText("DESTINATION ");

        jLabel3.setText("DATE");

        jLabel4.setText("SOURCE ");

        jRadioButton1.setText("SLEEPER");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("AC");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYSORE", "KANGERI", "KSR BENGALURU", "KR PURAM", "JOLARPET", "CHENNAI", "VIJAYWADA", "NAGPUR", "BETUL", "ITARSI", "JABALPUR", "ALLAHABAAD", "DIN DHAYAL UPADHYAY", "BUXAR", "ARRA", "DANAPUR", "PATNA", "SAMASTIPUR", "MUZAFFARPUR", "DARBHANGA" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYSORE", "KANGERI", "KSR BENGALURU", "KR PURAM", "JOLARPET", "CHENNAI", "VIJAYWADA", "NAGPUR", "BETUL", "ITARSI", "JABALPUR", "ALLAHABAAD", "DIN DHAYAL UPADHYAY", "BUXAR", "ARRA", "DANAPUR", "PATNA", "SAMASTIPUR", "MUZAFFARPUR", "DARBHANGA" }));

        jLabel5.setText("ENTER NAME");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("NOTE:FOR CANCELLATION ENTER YOUR NAME,DATE,CLASS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(jLabel6)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jRadioButton2.isSelected())
        {
            String n=jTextField1.getText();
            int q=jComboBox2.getSelectedIndex();
            int i=0;
            int p=jComboBox1.getSelectedIndex();
            String str1 = Integer.toString(p);
            String str2 = Integer.toString(q);
            int[] sour=new int[50];
            int[] dest=new int[50];

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Locale.getDefault();
            String d=sdf.format(jDateChooser1.getDate());
            try
            {
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                String sql="Select * from b_res_ac where dat=? ";
                java.sql.PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,d);
                java.sql.ResultSet rs=pst.executeQuery();
                int found=0;
                while(rs.next())
                {
                    found++;
                }
                if(found==0)
                {Class.forName("java.sql.DriverManager");
                    java.sql.Connection con1 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                    java.sql.Statement stmt1 =con1.createStatement();
                    String query1="INSERT INTO b_res_ac VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                    int rs1=stmt1.executeUpdate(query1);
                    JOptionPane.showMessageDialog(null,"TICKET IS BOOKED VIA RAILWAY WALLET!");
                    System.exit(0);
                }
                else
                {
                    Class.forName("java.sql.DriverManager");
                    java.sql.Connection con2 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");
                    String sql2="Select si,di from b_res_ac where dat=? ";
                    java.sql.PreparedStatement pst2=con2.prepareStatement(sql2);
                    pst2.setString(1,d);
                    java.sql.ResultSet rs2=pst.executeQuery();
                    while(rs2.next())
                    {
                        sour[i]=rs2.getInt("si");
                        dest[i]=rs2.getInt("di");
                        if((p==sour[i])&&(q==dest[i]))
                        {
                            JOptionPane.showMessageDialog(null,"NO TICKETS AVILABLE ON SLECTED DATE PLEASE TRY OTHER DATE");
                            break;
                        }
                        if((q<=sour[i]||p>=dest[i]))
                        {

                            Class.forName("java.sql.DriverManager");
                            java.sql.Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                            java.sql.Statement stmt3 =con3.createStatement();
                            str1= Integer.toString(p);
                            str2 = Integer.toString(q);
                            String query3="INSERT INTO b_res_ac VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                            int rs3=stmt3.executeUpdate(query3);

                            JOptionPane.showMessageDialog(null,"TICKET IS BOOKED VIA RAILWAY WALLET!");

                            System.exit(0);
                            break;
                        }
                        i++;
                    }
                    JOptionPane.showMessageDialog(null,"YOU ARE WAITLISTED PLEASE WAIT FOR ADMIN'S MESSAGE FOR CONFIRMATION STATUS");
                    Class.forName("java.sql.DriverManager");
                    java.sql.Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                    java.sql.Statement stmt3 =con3.createStatement();
                    str1= Integer.toString(p);
                    str2 = Integer.toString(q);
                    String query3="INSERT INTO b_ures_ac VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                    int rs3=stmt3.executeUpdate(query3);
                    System.exit(0);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        if(jRadioButton1.isSelected())
        {
            String n=jTextField1.getText();
            int q=jComboBox2.getSelectedIndex();
            int i=0;
            int p=jComboBox1.getSelectedIndex();
            String str1 = Integer.toString(p);
            String str2 = Integer.toString(q);
            int[] sour=new int[50];
            int[] dest=new int[50];

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            Locale.getDefault();
            String d=sdf.format(jDateChooser1.getDate());
            try
            {
                Class.forName("java.sql.DriverManager");
                java.sql.Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                String sql="Select * from b_res_s where dat=? ";
                java.sql.PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,d);
                java.sql.ResultSet rs=pst.executeQuery();
                int found=0;
                while(rs.next())
                {
                    found++;
                }
                if(found==0)
                {Class.forName("java.sql.DriverManager");
                    java.sql.Connection con1 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                    java.sql.Statement stmt1 =con1.createStatement();
                    String query1="INSERT INTO b_res_s VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                    int rs1=stmt1.executeUpdate(query1);
                    JOptionPane.showMessageDialog(null,"TICKET IS BOOKED VIA RAILWAY WALLET!");
                    System.exit(0);
                }
                else
                {
                    Class.forName("java.sql.DriverManager");
                    java.sql.Connection con2 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");
                    String sql2="Select si,di from b_res_s where dat=? ";
                    java.sql.PreparedStatement pst2=con2.prepareStatement(sql2);
                    pst2.setString(1,d);
                    java.sql.ResultSet rs2=pst.executeQuery();
                    while(rs2.next())
                    {
                        sour[i]=rs2.getInt("si");
                        dest[i]=rs2.getInt("di");
                        if((p==sour[i])&&(q==dest[i]))
                        {
                            JOptionPane.showMessageDialog(null,"NO TICKETS AVILABLE ON SLECTED DATE PLEASE TRY OTHER DATE");
                            break;
                        }
                        if((q<=sour[i]||p>=dest[i]))
                        {

                            Class.forName("java.sql.DriverManager");
                            java.sql.Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                            java.sql.Statement stmt3 =con3.createStatement();
                            str1= Integer.toString(p);
                            str2 = Integer.toString(q);
                            String query3="INSERT INTO b_res_s VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                            int rs3=stmt3.executeUpdate(query3);

                            JOptionPane.showMessageDialog(null,"TICKET IS BOOKED VIA RAILWAY WALLET!");
                            System.exit(0);
                            break;
                        }
                        i++;
                    }
                    JOptionPane.showMessageDialog(null,"YOU ARE WAITLISTED PLEASE WAIT FOR ADMIN'S MESSAGE FOR CONFIRMATION STATUS");

                    Class.forName("java.sql.DriverManager");
                    java.sql.Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");

                    java.sql.Statement stmt3 =con3.createStatement();
                    str1= Integer.toString(p);
                    str2 = Integer.toString(q);
                    String query3="INSERT INTO b_ures_s VALUES('"+d+"','"+str1+"','"+str2+"','"+n+"');";
                    int rs3=stmt3.executeUpdate(query3);

                    System.exit(0);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jRadioButton2.isSelected())
        {
            try {
                // TODO add your handling code here:
                String ab=jTextField1.getText();
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                Locale.getDefault();
                String d=sdf.format(jDateChooser1.getDate());
                try {
                    Class.forName("java.sql.DriverManager");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(sanghmitra.class.getName()).log(Level.SEVERE, null, ex);
                }
                java.sql.Connection con4 = null;
                try {
                    con4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");
                } catch (SQLException ex) {
                    Logger.getLogger(sanghmitra.class.getName()).log(Level.SEVERE, null, ex);
                }

                String x = "delete from b_res_ac where name = ? and dat=?";
                java.sql.PreparedStatement preparedStmt = null;
                try {
                    preparedStmt = con4.prepareStatement(x);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                }
                try {
                    preparedStmt.setString(1, ab);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                }
                preparedStmt.setString(2, d);
                // execute the preparedstatement
                preparedStmt.execute();
                int rowsAffected = preparedStmt.executeUpdate();
               if(rowsAffected == 0) {
   JOptionPane.showMessageDialog(null, "TICKET CANCELLED");
   System.exit(0);
}
else{
    JOptionPane.showMessageDialog(null, "WRONG DETAILS PLEASE CHECK AGAIN", "notdeleted", JOptionPane.ERROR_MESSAGE);
}

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                System.exit(0);
            }

        }
        if(jRadioButton1.isSelected())
        {
            try {
                // TODO add your handling code here:
                String ab=jTextField1.getText();
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                Locale.getDefault();
                String d=sdf.format(jDateChooser1.getDate());
                try {
                    Class.forName("java.sql.DriverManager");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(sanghmitra.class.getName()).log(Level.SEVERE, null, ex);
                }
                java.sql.Connection con4 = null;
                try {
                    con4 = DriverManager.getConnection("jdbc:mysql://localhost:3306/sample1yog","root", "root");
                } catch (SQLException ex) {
                    Logger.getLogger(sanghmitra.class.getName()).log(Level.SEVERE, null, ex);
                }

                String x = "delete from b_res_s where name = ? and dat=?";
                java.sql.PreparedStatement preparedStmt = null;
                try {
                    preparedStmt = con4.prepareStatement(x);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                }
                try {
                    preparedStmt.setString(1, ab);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                }
                preparedStmt.setString(2, d);
                // execute the preparedstatement
                preparedStmt.execute();
                int rowsAffected = preparedStmt.executeUpdate();
                if(rowsAffected == 0) {
   JOptionPane.showMessageDialog(null, "TICKET CANCELLED");
   System.exit(0);
}
else{
    JOptionPane.showMessageDialog(null, "WRONG DETAILS PLEASE CHECK AGAIN", "notdeleted", JOptionPane.ERROR_MESSAGE);
}

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"NO TICKETS TO CANCEL ");
                System.exit(0);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bagmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bagmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bagmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bagmati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bagmati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
